### ISSUE TITLE
Use a higher precision timing method on Windows

### ISSUE THREAD

**Issue by JosephusPaye** [Fastcode/NUClear#47]
The current timing method used in ChronoController with the wait condition and spin lock is not very precise on Windows - timers below 15ms are unreliable, triggering at wildly varying intervals. Look into a [nanosleep equivalent on Windows](https://stackoverflow.com/a/13397746/5800506), to use in addition to the condition lock and spin lock used in ChronoController.hpp

**Comment by TrentHouliston** [comment]
This was addressed in #145
